spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  docker:
    compose:
      enabled: true
      profiles:
        active: db_pg_1
  sql:
    init:
      mode: never
security:
  user:
    service:
      default-role: ROLE_USER